---
apiVersion: v1
kind: Service
metadata:
  name: flask
  #namespace: default
  labels:
    app: flask
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30555
  selector:
    app: flask
