apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-docker
  namespace: gitlab
data:
  config.toml: |
    concurrent = 4
    check_interval = 1

    [[runners]]
      name = "gitlab-docker-runner"
      url = "http://gitlab.gitlab/ci"
      token = "a2c668d104311cac37c5615701f9e9"
      executor = "docker"
      [runners.docker]
        tls_verify = false
        image = "python:3.5"
        privileged = true
        disable_cache = false
        volumes = ["/cache"]
      [runners.cache]
        Type = "s3"
        ServerAddress = "http://minio.gitlab/"
        AccessKey = "NAQDF9PGV6IN6OUA1AWQ"
        SecretKey = "aqaDEnG1bMHJ9y4L3KjstZzMcG9d7vRgSJg28B1X"
        BucketName = "runner"
